### ISSUE TITLE
Invalid use of type(CPUDispatcher(<function euclid_dist at 0x7f5913a577b8>)) with parameters (array(float64, 1d, C), array(float64, 1d, C))

### ISSUE THREAD

**Issue by liygzting** [eamid/trimap#10]
hello 
@eamid 
Thank you very much for your work
when i try use it for my data ,but it get error

my data like:
array([1.3200e+02, 3.0000e+00, 3.4000e+01, 4.1000e+01, 4.3000e+01,
       9.0000e+02, 8.9700e+02, 1.2700e+02, 3.0000e+00, 1.7000e+01,
       3.5900e+02, 5.9800e+02, 1.0000e+00, 1.0000e+00, 9.3000e+01,
       3.0000e+00, 5.0000e+00, 1.8000e+01, 2.4500e+02, 4.2500e+02,
       4.0600e+02, 1.2100e+02, 3.0000e+00, 5.0000e+00, 1.8000e+01,
       7.8400e+02, 1.4690e+03, 1.1610e+03, 1.1000e+02, 3.0000e+00,
       1.5000e+01, 2.0000e+02, 2.1200e+02, 6.7700e+02, 6.5400e+02,
       1.1000e+02, 3.0000e+00, 3.4000e+01, 4.1000e+01, 4.3000e+01,
       1.0940e+03, 1.0880e+03, 1.1000e+02, 4.0000e+00, 2.9000e+01,
...
])

get

TRIMAP(n_inliers=20, n_outliers=10, n_random=10, distance=euclidean, lr=1000.0, n_iters=400, weight_adj=1000.0, apply_pca=True, opt_method=dbd, verbose=True, return_seq=False)
running TriMap on 1900000 points with dimension 500
pre-processing
applied PCA
found nearest neighbors
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/root/anaconda3/lib/python3.6/site-packages/trimap-1.0.14-py3.6.egg/trimap/trimap_.py", line 827, in fit_transform
  File "/root/anaconda3/lib/python3.6/site-packages/trimap-1.0.14-py3.6.egg/trimap/trimap_.py", line 812, in fit
  File "/root/anaconda3/lib/python3.6/site-packages/trimap-1.0.14-py3.6.egg/trimap/trimap_.py", line 583, in trimap
  File "/root/anaconda3/lib/python3.6/site-packages/trimap-1.0.14-py3.6.egg/trimap/trimap_.py", line 318, in generate_triplets
  File "/root/anaconda3/lib/python3.6/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/root/anaconda3/lib/python3.6/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/root/anaconda3/lib/python3.6/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of type(CPUDispatcher(<function euclid_dist at 0x7f5913a577b8>)) with parameters (array(float64, 1d, C), array(float64, 1d, C))
Known signatures:
 * (array(float32, 1d, A), array(float32, 1d, A)) -> float32
During: resolving callee type: type(CPUDispatcher(<function euclid_dist at 0x7f5913a577b8>))
During: typing of call at /root/anaconda3/lib/python3.6/site-packages/trimap-1.0.14-py3.6.egg/trimap/trimap_.py (94)

File "../../anaconda3/lib/python3.6/site-packages/trimap-1.0.14-py3.6.egg/trimap/trimap_.py", line 94:
<source missing, REPL/exec in use?>

**Comment by eamid** [comment]
Hi,

There seems to be a problem with your packages. Please do a `conda update` and check if it fixes the problem.
